apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: manoj
spec:
  replicas: 7
  selector:
    matchLabels:
     app: tomcat
  template:
    metadata:
     labels:
       app: tomcat
    spec:
     imagePullSecrets:
       - name: passwd-for-custom-di
     containers:
       - name: tomcat
         image:  maanoj1991/tomcat:BUILD_NUMBER
         ports:
          - containerPort: 8080
